
// import type { Metadata } from "next";
// import { Vazirmatn } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// import LayoutClient from "./LayoutClient";

// const vazirmatn = Vazirmatn({
//   variable: "--font-vazirmatn",
//   subsets: ["arabic"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="fa" suppressHydrationWarning>
//       <body className={` ${vazirmatn.className} antialiased`}>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="dark"
//           enableSystem={false}
//           disableTransitionOnChange
//         >
//               <LayoutClient>
//              {children}
//               </LayoutClient>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutClient from "./LayoutClient";

const arad = localFont({
  src: "../../public/fonts/arad/AradVF.woff2",
  variable: "--font-arad",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" suppressHydrationWarning>
      <body className={`${arad.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <LayoutClient>{children}</LayoutClient>
        </ThemeProvider>
      </body>
    </html>
  );
}